version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: hello-nginx
    ports:
      - "5500:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped